### PR TITLE
[DEV-5733] calc pr metrics multiple jira groups

### PR DESCRIPTION
**Pull request by gaetano-guerriero**
Support more JIRAFilter in calc_pull_requests_metrics_line()
I/O will come later.

This change is [Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3272)

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
*[`server/athenian/api/internal/features/entries.py` line 342 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYNmfo4GM7342DKiNQ:-NMYNmfo4GM7342DKiNR:b67jpes) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L342)):*
> ```Python
>         participants: list[PRParticipants],
>         labels: LabelFilter,
>         jiragroups: Sequence[JIRAFilter],
> ```

How about `jiras`? To match the rest of the parameter names.

**Comment by vmarkovtsev** [comment]
*[`server/athenian/api/internal/features/entries.py` line 372 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYOSf0A5oEasLCarqN:-NMYOBmX2Arp1QiwIa2e:bdrvcyk) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L372)):*
> ```Python
>         if not jiragroups:
>             jiragroups = [JIRAFilter.empty()]
>         global_jira_filter = reduce(operator.or_, jiragroups)
> ```

I would write a `JIRAFilter.combine()` staticmethod to do this. Potentially, in a single pass for efficiency.

**Comment by vmarkovtsev** [comment]
*[`server/athenian/api/internal/features/entries.py` line 1548 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYPNxO40cSV24YjnGD:-NMYPNxO40cSV24YjnGE:b-qn8qvy) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L1548)):*
> ```Python
>     ) -> _JIRAFilterToGroupingConverter:
>         actual_filters = [f for f in all_filters if f]
>         if any((f.priorities or f.issue_types) for f in actual_filters):
> ```

We have a strong, perpetual guarantee that there is only one jira account. We must assert it unconditionally. Also, we must accept only meaningful JIRA filters.



_Code quote (i):_
```Python
        actual_filters = [f for f in all_filters if f]
        if any((f.priorities or f.issue_types) for f in actual_filters):
            jira_acc_ids = [f.account for f in actual_filters]
```



_Code snippet (ii):_
```Python
jira_acc_id = entities_mapper = None
for f in all_filters:
    assert f
    if jira_acc_id is None:
        jira_acc_id = f.account
    else:
        assert jira_acc_id = f.account
    if f.priorities or f.issue_types:
        entities_mapper = await JIRAEntitiesMapper.load(jira_acc_id, mdb)
```

**Comment by vmarkovtsev** [comment]
*[`server/athenian/api/internal/miners/filters.py` line 250 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYRG6o1RX87eSIYOAe:-NMYRG6o1RX87eSIYOAf:b-w9czbo) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/miners/filters.py#L250)):*
> ```Python
> 
>     @classmethod
>     def with_defaults(cls, *, account: int, **kwargs: Any) -> JIRAFilter:
> ```

How about giving default values to the dataclass fields then?

**Comment by vmarkovtsev** [comment]
*[`server/athenian/api/internal/miners/filters.py` line 148 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYRekd7KX-Xm83K2Hi:-NMYRekd7KX-Xm83K2Hj:b-8svtyw) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/miners/filters.py#L148)):*
> ```Python
>             epics = _join_filter_sets(self.epics, other.epics)
> 
>         projects = self.projects | other.projects  # guaranteed to be filled in both
> ```

Therefore, our `combine()` would call `set.union(*(x.projects for x in jiras))` which should reduce the number of temporary sets.
There are JIRA accounts with hundreds of projects, statuses, etc., and can already penalty the performance a bit.

**Comment by vmarkovtsev** [comment]
*[`server/athenian/api/models/web/calculated_linear_metric_values.py` line 18 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYS9G622IBzb73lH7z:-NMYS9G7BGjQJC32xsMj:undefined) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/models/web/calculated_linear_metric_values.py#L18)):*
> ```Python
>     def clean_up_confidence_fields(self) -> None:
>         """Clear the confidence fields when `confidence_scores` contains nothing, in place."""
>         if self.confidence_scores is None or not any(
> ```





_Code quote (i):_
```Python
        if self.confidence_scores is None or not any(
            score is not None for score in self.confidence_scores
        ):
```



_Code snippet (ii):_
```Python
if all(score is None for score in self.confidence_scores or ()):
```

**Review by vmarkovtsev — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3272)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @gaetano-guerriero)

**Review by gaetano-guerriero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3272)* status: 2 of 9 files reviewed, 6 unresolved discussions (waiting on @vmarkovtsev)

___
*[`server/athenian/api/internal/features/entries.py` line 342 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYNmfo4GM7342DKiNQ:-NMYYNi73FVPh1qljKvI:b6zt4ms) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L342)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

How about `jiras`? To match the rest of the parameter names.
</blockquote></details>

I think with `jiragroups` you more clearly understand you are going to split the result, not just changing it.
`jiragroups` is equivalent to `repogroups` ( and especially `withgroups`), so you must match it with other `*groups`fields. 
___
*[`server/athenian/api/internal/features/entries.py` line 372 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYOSf0A5oEasLCarqN:-NMZ5SzQ4beOVfhEb2H1:b-896fix) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L372)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

I would write a `JIRAFilter.combine()` staticmethod to do this. Potentially, in a single pass for efficiency.
</blockquote></details>

Done.
___
*[`server/athenian/api/internal/features/entries.py` line 1548 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYPNxO40cSV24YjnGD:-NMZ5u-L3O7tUeh4_kwC:bfkrs81) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L1548)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

We have a strong, perpetual guarantee that there is only one jira account. We must assert it unconditionally. Also, we must accept only meaningful JIRA filters.
</blockquote></details>

Why do we have to accept only meaningful JIRA filters ? Callers should not bother with handling JIRAFilter.empty() by themselves
___
*[`server/athenian/api/internal/miners/filters.py` line 148 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYRekd7KX-Xm83K2Hi:-NMZ5JkC9E3aGxwgDI2N:b-896fix) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/miners/filters.py#L148)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

Therefore, our `combine()` would call `set.union(*(x.projects for x in jiras))` which should reduce the number of temporary sets.
There are JIRA accounts with hundreds of projects, statuses, etc., and can already penalty the performance a bit.
</blockquote></details>

Done.
___
*[`server/athenian/api/internal/miners/filters.py` line 250 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYRG6o1RX87eSIYOAe:-NMYXTN14nPjNel6-kxF:b-896fix) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/miners/filters.py#L250)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

How about giving default values to the dataclass fields then?
</blockquote></details>

Done.
___
*[`server/athenian/api/models/web/calculated_linear_metric_values.py` line 18 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYS9G622IBzb73lH7z:-NMYXwU74S1n4SdqXtl6:b8rz942) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/models/web/calculated_linear_metric_values.py#L18)):*
> ```Python
>     def clean_up_confidence_fields(self) -> None:
>         """Clear the confidence fields when `confidence_scores` contains nothing, in place."""
>         if self.confidence_scores is None or not any(
> ```

should this be true also when `confidence_scores` is an empty sequence ?

**Review by vmarkovtsev — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 1 of 3 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3272)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @gaetano-guerriero)

___
*[`server/athenian/api/internal/features/entries.py` line 342 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYNmfo4GM7342DKiNQ:-NMZafv-7KARAAg7qB8B:bepckfn) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L342)):*
<details><summary><i>Previously, gaetano-guerriero wrote…</i></summary><blockquote>

I think with `jiragroups` you more clearly understand you are going to split the result, not just changing it.
`jiragroups` is equivalent to `repogroups` ( and especially `withgroups`), so you must match it with other `*groups`fields. 

</blockquote></details>

It's important to stick to existing naming conventions here to stay uniform. The spec has `jiragroups` and that's :100:  but in this function signature we don't have any prior mention of `groups`. 
___
*[`server/athenian/api/internal/features/entries.py` line 1548 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYPNxO40cSV24YjnGD:-NMZb6Fh680QvAat1ycU:b7bxrjg) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L1548)):*
<details><summary><i>Previously, gaetano-guerriero wrote…</i></summary><blockquote>

Why do we have to accept only meaningful JIRA filters ? Callers should not bother with handling JIRAFilter.empty() by themselves
</blockquote></details>

Yes, I see it now, we put a single empty filter if there is no jira. How about the following snippet, then? The goal is to avoid excessive comprehensions and make the code clearer. We had the same fallacy in C# circa 2010 when they added LINQ and everyone wanted to rewrite the "boring" for loops to new fancy syntax. The for loops have one big advantage: they are always easy to read.



_Code snippet:_
```Python
jira_acc_id = entities_mapper = None
for f in all_filters:
    if not f:
        continue
    if jira_acc_id is None:
        jira_acc_id = f.account
    else:
        assert jira_acc_id == f.account
    if f.priorities or f.issue_types:
        entities_mapper = await JIRAEntitiesMapper.load(jira_acc_id, mdb)
```
___
*[`server/athenian/api/internal/miners/filters.py` line 267 at r3](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMZcnp28h3NbZAVn1FI:-NMZcnp28h3NbZAVn1FJ:undefined) ([raw file](https://github.com/athenianco/athenian-api/blob/4aeb249d8a2f9e356bfa7d5279f35a13af0f77fb/server/athenian/api/internal/miners/filters.py#L267)):*
> ```Python
> 
> def _join_filter_sets(*sets: frozenset) -> frozenset:
>     if any(not s for s in sets):
> ```





_Code snippet:_
```Python
if not all(sets):
```
___
*[`server/athenian/api/models/web/calculated_linear_metric_values.py` line 18 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYS9G622IBzb73lH7z:-NMZd5Bw5JQEdF83Nezj:b-n0uqq1) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/models/web/calculated_linear_metric_values.py#L18)):*
<details><summary><i>Previously, gaetano-guerriero wrote…</i></summary><blockquote>

should this be true also when `confidence_scores` is an empty sequence ?
</blockquote></details>

It should be OK, unless there is a specific test that fails.

**Review by gaetano-guerriero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3272)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @vmarkovtsev)

___
*[`server/athenian/api/internal/features/entries.py` line 342 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYNmfo4GM7342DKiNQ:-NMburW82AZ-9mDzWq2W:bubenuj) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L342)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

It's important to stick to existing naming conventions here to stay uniform. The spec has `jiragroups` and that's :100:  but in this function signature we don't have any prior mention of `groups`. 
</blockquote></details>

Done.
OK I misread the comment as being about the field in the request, for internal method I agree that `jiras` is better
___
*[`server/athenian/api/internal/features/entries.py` line 1548 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYPNxO40cSV24YjnGD:-NMbwqhF8uCs1k9-8tfb:blq4ojl) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L1548)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

Yes, I see it now, we put a single empty filter if there is no jira. How about the following snippet, then? The goal is to avoid excessive comprehensions and make the code clearer. We had the same fallacy in C# circa 2010 when they added LINQ and everyone wanted to rewrite the "boring" for loops to new fancy syntax. The for loops have one big advantage: they are always easy to read.
</blockquote></details>

It's not about being boring it's about having three conditions inside the loop and two extra exit points in the loop.
Anyway, o we `break` after entities_mapper ? Or we wan't to check next filters `.account` validity ? 
If  we don't check the following filters we can also remove the `assert`, we just trust the input.
___
*[`server/athenian/api/internal/miners/filters.py` line 267 at r3](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMZcnp28h3NbZAVn1FI:-NMbvEiS2v8wn1elaYdr:b-896fix) ([raw file](https://github.com/athenianco/athenian-api/blob/4aeb249d8a2f9e356bfa7d5279f35a13af0f77fb/server/athenian/api/internal/miners/filters.py#L267)):*
> ```Python
> 
> def _join_filter_sets(*sets: frozenset) -> frozenset:
>     if any(not s for s in sets):
> ```

Done.
___
*[`server/athenian/api/models/web/calculated_linear_metric_values.py` line 18 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYS9G622IBzb73lH7z:-NMbvbsNApNuGpjzKR8M:b-896fix) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/models/web/calculated_linear_metric_values.py#L18)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

It should be OK, unless there is a specific test that fails.
</blockquote></details>

Done.

**Review by gaetano-guerriero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3272)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @vmarkovtsev)

___
*[`server/athenian/api/internal/features/entries.py` line 1548 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYPNxO40cSV24YjnGD:-NMc8uIL1sISCPo-r5ab:b99tt0i) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L1548)):*
<details><summary><i>Previously, gaetano-guerriero wrote…</i></summary><blockquote>

It's not about being boring it's about having three conditions inside the loop and two extra exit points in the loop.
Anyway, o we `break` after entities_mapper ? Or we wan't to check next filters `.account` validity ? 
If  we don't check the following filters we can also remove the `assert`, we just trust the input.
</blockquote></details>

I'm meaning this
```
        for f in all_filters:
            if f and (f.priorities or f.issue_types):
                entities_mapper = await JIRAEntitiesMapper.load(f.account, mdb)
                break
        else:
            entities_mapper = None
```

**Review by vmarkovtsev — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3272)* status: 4 of 9 files reviewed, all discussions resolved

___
*[`server/athenian/api/internal/features/entries.py` line 1548 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3272#-NMYPNxO40cSV24YjnGD:-NMciWuo9PQEpIYBQ7lC:bubsn4f) ([raw file](https://github.com/athenianco/athenian-api/blob/a11c3caf1fa1da1ed223bf5910e72ce1ea6aa7d5/server/athenian/api/internal/features/entries.py#L1548)):*
<details><summary><i>Previously, gaetano-guerriero wrote…</i></summary><blockquote>

I'm meaning this
```
        for f in all_filters:
            if f and (f.priorities or f.issue_types):
                entities_mapper = await JIRAEntitiesMapper.load(f.account, mdb)
                break
        else:
            entities_mapper = None
```
</blockquote></details>

Don't wanna further block this, the current code is working and there are edge cases taken into account => resolve.

**Pull request merged**
