### PR TITLE
[DEV-5005] gql metrics fix jira priority filtering

### PR DESCRIPTION
**Pull request by gaetano-guerriero**

### CODE REVIEW

**Review by vmarkovtsev — APPROVED** [review]

**Comment by vmarkovtsev** [comment]
@gaetano-guerriero there is a conflict

**Comment by gaetano-guerriero** [comment]
Rebased

**Comment by vmarkovtsev** [comment]
@gaetano-guerriero It's failing CI now

**Comment by gaetano-guerriero** [comment]
fixed

**Review by vmarkovtsev — APPROVED** [review]

**Pull request merged**
