### PR TITLE
[DEV-5738] metrics jira labels grouping

### PR DESCRIPTION
**Pull request by gaetano-guerriero**
This change is [Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3403)

### CODE REVIEW

**Review by gaetano-guerriero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3403)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`server/athenian/api/internal/features/entries.py` line 1299 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3403#-NOxJj4m4uEVPQVNUg6N:-NOxJj4n45M7c9YBp2kZ:bbg5w4h) ([raw file](https://github.com/athenianco/athenian-api/blob/66d9bffaeead891530893721cbade292590c170f/server/athenian/api/internal/features/entries.py#L1299)):*
> ```Python
>         # do not consider components as labels when split_by_label to keep historical behavior
>         if not split_by_label and Issue.labels in extra_columns:
>             # pandas warning during groupby without this, doesn't like the bytes index
> ```

@vmarkovtsev if you know something here happy to remove the hack

**Review by vmarkovtsev — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3403)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @gaetano-guerriero)

___
*[`server/athenian/api/internal/features/entries.py` line 1299 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3403#-NOxJj4m4uEVPQVNUg6N:-NPIlU2--ueyvOM1es_T:b-itnbep) ([raw file](https://github.com/athenianco/athenian-api/blob/66d9bffaeead891530893721cbade292590c170f/server/athenian/api/internal/features/entries.py#L1299)):*
<details><summary><i>Previously, gaetano-guerriero wrote…</i></summary><blockquote>

@vmarkovtsev if you know something here happy to remove the hack 
</blockquote></details>

Yeah, we shouldn't do this. This will put us on the knees in production. This materialize tens of thousands of bytes and that will destroy the performance.

We should avoid groupby in pandas whatsoever. Use `np.unique()` and `np.argsort()`. We do a lot of that in athenian/api/internal/features/github/check_run_metrics.py, for example.
___
*[`server/athenian/api/internal/features/metric_calculator.py` line 1203 at r2](https://reviewable.io/reviews/athenianco/athenian-api/3403#-NPImEi2EVJl8h4y6FcV:-NPImEi2EVJl8h4y6FcW:b-9tk7vd) ([raw file](https://github.com/athenianco/athenian-api/blob/a47e11fc957d56d2d009527aa02c0fb57fa626c4/server/athenian/api/internal/features/metric_calculator.py#L1203)):*
> ```Python
>             DETAILS = PR_JIRA_DETAILS_COLUMN_MAP
> 
>             df_matches = np.full(len(df), True, dtype=bool)
> ```

We usually use the `df_` prefix for real dataframes. Let's use a different name to reduce the confusion.
___
*[`server/athenian/api/internal/features/metric_calculator.py` line 1221 at r2](https://reviewable.io/reviews/athenianco/athenian-api/3403#-NPImX4CBFF1EuR47SQZ:-NPImX4CBFF1EuR47SQ_:b-uwm7hn) ([raw file](https://github.com/athenianco/athenian-api/blob/a47e11fc957d56d2d009527aa02c0fb57fa626c4/server/athenian/api/internal/features/metric_calculator.py#L1221)):*
> ```Python
>                         not_maching_mask = np.ones(len(df_values), dtype=bool)
>                         not_maching_mask[matching] = False
>                         df_matches[not_maching_mask] = False
> ```

Will this work?



_Code snippet:_
```Python
df_matches[~matching] = False
```

**Review by gaetano-guerriero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3403)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @vmarkovtsev)

___
*[`server/athenian/api/internal/features/entries.py` line 1299 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3403#-NOxJj4m4uEVPQVNUg6N:-NPM0jHL0BTEWX2J0p3V:b-454rde) ([raw file](https://github.com/athenianco/athenian-api/blob/66d9bffaeead891530893721cbade292590c170f/server/athenian/api/internal/features/entries.py#L1299)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

Yeah, we shouldn't do this. This will put us on the knees in production. This materialize tens of thousands of bytes and that will destroy the performance.

We should avoid groupby in pandas whatsoever. Use `np.unique()` and `np.argsort()`. We do a lot of that in athenian/api/internal/features/github/check_run_metrics.py, for example.
</blockquote></details>

I propose to move this forward and to create a task to vectorize `import_components_as_labels` which I will do shortly. This should indirectly resolve the warning. 
This code path it's only used in the new UI interface anyway, so maybe the improvement will land before of the UI.

Meanwhile I'm changing the hack to `issues.reset_index(drop=True, inplace=True)` which is faster, we don't  need the values in the index at all.
___
*[`server/athenian/api/internal/features/metric_calculator.py` line 1203 at r2](https://reviewable.io/reviews/athenianco/athenian-api/3403#-NPImEi2EVJl8h4y6FcV:-NPLwzLX-KaubHgNoG8v:b-896fix) ([raw file](https://github.com/athenianco/athenian-api/blob/a47e11fc957d56d2d009527aa02c0fb57fa626c4/server/athenian/api/internal/features/metric_calculator.py#L1203)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

We usually use the `df_` prefix for real dataframes. Let's use a different name to reduce the confusion.
</blockquote></details>

Done.
___
*[`server/athenian/api/internal/features/metric_calculator.py` line 1221 at r2](https://reviewable.io/reviews/athenianco/athenian-api/3403#-NPImX4CBFF1EuR47SQZ:-NPLzT7L7e54nC1L_zht:bar09dr) ([raw file](https://github.com/athenianco/athenian-api/blob/a47e11fc957d56d2d009527aa02c0fb57fa626c4/server/athenian/api/internal/features/metric_calculator.py#L1221)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

Will this work?
</blockquote></details>

I reworked this to use indexes instead of a boolean mask like `group_pr_facts_by_jira`, please check

**Review by vmarkovtsev — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3403)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @gaetano-guerriero)

___
*[`server/athenian/api/internal/features/metric_calculator.py` line 1221 at r2](https://reviewable.io/reviews/athenianco/athenian-api/3403#-NPImX4CBFF1EuR47SQZ:-NPMQMHz7nMjq8V8Fre_:b-idqw5b) ([raw file](https://github.com/athenianco/athenian-api/blob/a47e11fc957d56d2d009527aa02c0fb57fa626c4/server/athenian/api/internal/features/metric_calculator.py#L1221)):*
<details><summary><i>Previously, gaetano-guerriero wrote…</i></summary><blockquote>

I reworked this to use indexes instead of a boolean mask like `group_pr_facts_by_jira`, please check
</blockquote></details>

Let's combine the two to reduce memory pressure.



_Code quote (i):_
```Python
 matches[matching] += 1
```



_Code snippet (ii):_
```Python
 matches[labels_matcher(filter_values)] += 1
```
___
*[`server/athenian/api/internal/features/metric_calculator.py` line 1224 at r3](https://reviewable.io/reviews/athenianco/athenian-api/3403#-NPMQXGm4zVzf-i9Rsgo:-NPMQXGm4zVzf-i9Rsgp:b-2guby3) ([raw file](https://github.com/athenianco/athenian-api/blob/ca663e9f18d10c3b45b3a4918e68ea1e2624280e/server/athenian/api/internal/features/metric_calculator.py#L1224)):*
> ```Python
>                     else:
>                         prop_matches = in1d_str(values, filter_values)
>                         matches[prop_matches] += 1
> ```

same here

**Review by vmarkovtsev — APPROVED** [review]
Approving to unblock, supposing that the minor comments will be fixed.

> Reviewed 1 of 5 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3403#-:-NPMRhhCD48RKcDNa5DJ:bvtqvvo)* status: all files reviewed, 2 unresolved discussions (waiting on @gaetano-guerriero)

**Review by gaetano-guerriero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3403)* status: all files reviewed, 2 unresolved discussions (waiting on @vmarkovtsev)

___
*[`server/athenian/api/internal/features/metric_calculator.py` line 1221 at r2](https://reviewable.io/reviews/athenianco/athenian-api/3403#-NPImX4CBFF1EuR47SQZ:-NPMb8tg8vHOmgZFPQQR:b-896fix) ([raw file](https://github.com/athenianco/athenian-api/blob/a47e11fc957d56d2d009527aa02c0fb57fa626c4/server/athenian/api/internal/features/metric_calculator.py#L1221)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

Let's combine the two to reduce memory pressure.
</blockquote></details>

Done.
___
*[`server/athenian/api/internal/features/metric_calculator.py` line 1224 at r3](https://reviewable.io/reviews/athenianco/athenian-api/3403#-NPMQXGm4zVzf-i9Rsgo:-NPMbIHt0RMLFCtyKwed:b-896fix) ([raw file](https://github.com/athenianco/athenian-api/blob/ca663e9f18d10c3b45b3a4918e68ea1e2624280e/server/athenian/api/internal/features/metric_calculator.py#L1224)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Pull request merged**
